# Generated by Django 4.2.9 on 2024-01-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="deadLine",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="todo",
            name="finishedAt",
            field=models.DateField(null=True),
        ),
    ]
